language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: "pip install --editable ."
# command to run tests
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then py.test; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pytest; fi"
